### ISSUE TITLE
Problems reading titles form Nature Review, Cell Reports and others 

### ISSUE THREAD

**Issue by carlosapinzona** [heversonbr/scientific-paper-pdf-rename#3]
This Code is amazing! but there are still things that could be improved some papers docent recognize the text of the title but the type of article I have attached examples.

[
[Reviews.pdf](https://github.com/heversonbr/scientific-paper-pdf-rename/files/13517404/Reviews.pdf)
[Report.pdf](https://github.com/heversonbr/scientific-paper-pdf-rename/files/13517405/Report.pdf)
](url)

**Comment by heversonbr** [comment]
Thanks for your feedback. Fully agree with you, there's a lot space to improved yet. 
The explanation for the examples you sent is quite straightforward: the script just seeks the sentence with the larger font in the first two pages. When the larger font is not the title it will give a wrong. :-(  
It works well for a large set of computer science articles , this is what I had in mind when I started that, I guess I will have to try different approaches. Im planning to port it to Rust and I hope to improve it soon.

**Comment by heversonbr** [comment]
Thanks for your feedback. Fully agree with you, there's a lot space to improved yet.
The explanation for the examples you sent is quite straightforward: the script just seeks the sentence with the larger font in the first two pages. When the larger font is not the title it will give a wrong. :-(
It works well for a large set of computer science articles , this is what I had in mind when I started that, I guess I will have to try different approaches. Im planning to port it to Rust and I hope to improve it soon.

**Comment by heversonbr** [comment]
Thanks for your feedback. Fully agree with you, there's a lot space to improved yet.
The explanation for the examples you sent is quite straightforward: the script just seeks the sentence with the larger font in the first two pages. When the larger font is not the title it will give a wrong. :-(
It works well for a large set of computer science articles , this is what I had in mind when I started that, I guess I will have to try different approaches. Im planning to port it to Rust and I hope to improve it soon.

**Comment by heversonbr** [comment]
Thanks for your feedback. Fully agree with you, there's a lot space to improved yet.
The explanation for the examples you sent is quite straightforward: the script just seeks the sentence with the larger font in the first two pages. When the larger font is not the title it will give a wrong. :-(
It works well for a large set of computer science articles , this is what I had in mind when I started that, I guess I will have to try different approaches. Im planning to port it to Rust and I hope to improve it soon.
